### ISSUE TITLE
Is there a way to mute stderror?

### ISSUE THREAD

**Issue by PierBover** [bbc/audiowaveform#138] opened 2021-06-04 19:09 UTC
I'm using `audiowaveform` and it's sending non-error info to `stderror`.

FFmpeg also does this, but it can be muted with `-loglevel error` so that only errors are sent to `stderror`. This is useful for example when running it in a server.

Is there a way to solve this with `audiowaveform`?

**Comment by chrisn** [comment] 2021-06-04 20:22
Currently, no. I think I started working on a `--quiet` option a long time ago, but never got round to finishing it. I'll close as this is essentially a duplicate of https://github.com/bbc/audiowaveform/issues/25.

**Closed by chrisn** 2021-06-04 20:22 UTC
